### ISSUE TITLE
STG: Stage 1 issue

### ISSUE THREAD

**Issue by Ryu1845** [unilight/seq2seq-vc#10]
Hello, I'm having an issue with the recipe in `egs/l2-arctic/stg`.
Here's the log from `data/bdl2TXHC_ppg_sxliu_dev/decode.log`.
```
# s3prl-vc-decode --scp data/bdl_dev/wav.scp --checkpoint downloads/s3prl-vc-ppg_sxliu/checkpoint-50000steps.pkl --trg-stats downloads/s3prl-vc-ppg_sxliu/stats.h5 --outdir data/bdl2TXHC_ppg_sxliu_dev --verbose 1 
# Started at Mon Feb 26 16:31:07 UTC 2024
#
/home/smejjoute/work/seq2seq-vc/.venv/lib/python3.10/site-packages/s3prl/upstream/byol_s/byol_a/common.py:20: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("sox_io")
['/home/smejjoute/work/seq2seq-vc/egs/arctic/vc1/downloads/cmu_us_bdl_arctic/wav/arctic_b0440.wav']
Traceback (most recent call last):
  File "/home/smejjoute/work/seq2seq-vc/.venv/bin/s3prl-vc-decode", line 8, in <module>
    sys.exit(main())
  File "/home/smejjoute/work/seq2seq-vc/.venv/lib/python3.10/site-packages/s3prl_vc/bin/decode.py", line 157, in main
    dataset = AudioSCPMelDataset(
  File "/home/smejjoute/work/seq2seq-vc/.venv/lib/python3.10/site-packages/s3prl_vc/datasets/datasets.py", line 259, in __init__
    len(contents[1:]) > 0
AssertionError: during inference, please append speaker embedding source files at the end of each line.
# Accounting: time=4 threads=1
# Ended (code 1) at Mon Feb 26 16:31:11 UTC 2024, elapsed time 4 seconds
```

**Comment by Ryu1845** [comment]
I am running all of the stages (I just ran `./run.sh` with the variables changed to the correct paths).

**Comment by unilight** [comment]
@Ryu1845 I apologize for the bug. The error was due to some bug in the s3prl-vc package. I need some time to fix it and test it. Please wait patiently. Thanks!

**Comment by Ryu1845** [comment]
Thank you for your response!

**Comment by unilight** [comment]
@Ryu1845 I apologize for replying so late. Can you try updating the `s3prl-vc` package by executing the following?
```
cd tools
make s3prl_vc
```
And then see if you get the same error. If not, please paste the error log again.

**Comment by Ryu1845** [comment]
Hi, this seems to have fixed the stage 1 issue, but now I'm having an issue in stage 4 `ModuleNotFoundError: No module named 'seq2seq_vc.losses.diffsinger_l2_loss'`
