### ISSUE TITLE
use_guided_attn_loss

### ISSUE THREAD

**Issue by leelee724** [unilight/seq2seq-vc#11]
Hello author, I want to add guided_attention_loss during training. I have added "use_guided_attn_loss: true" to the config, but the following error message will appear. How to solve it? Thank you!

The error message is as follows:
Traceback (most recent call last):
   File "/home/user/000_VC/seq2seq-vc/egs/0412/stage4A_2_v10_guide_attn_loss/../../../seq2seq_vc/bin/vc_train.py", line 500, in <module>
     main()
   File "/home/user/000_VC/seq2seq-vc/egs/0412/stage4A_2_v10_guide_attn_loss/../../../seq2seq_vc/bin/vc_train.py", line 411, in main
     criterion = {
   File "/home/user/000_VC/seq2seq-vc/egs/0412/stage4A_2_v10_guide_attn_loss/../../../seq2seq_vc/bin/vc_train.py", line 412, in <dictcomp>
     criterion_class: getattr(seq2seq_vc.losses, criterion_class)(
AttributeError: module 'seq2seq_vc.losses' has no attribute 'guided_attn'

**Comment by unilight** [comment]
Hi @leelee724, unfortunately the guided attention loss is not supported in this repo... also based on my informal experiments, it does not have a significant impact on the convergence speed nor the quality of the generated speech.
